server:
  port: 8000
  metricsPath: "/vitals"
  metricsPort: 9000
  metricsPrefix: "api_server"

# Control plane state service
database: 
  uri: mongodb://localhost:27017
  
environments:
  local:
   
  dev: 